AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Coming Home Alert

Parameters:
  PhoneNumber:
    Type: String
    Description: The phone number to send the message to using international dialing format and no spaces.
    ConstraintDescription: Must match the pattern ^\+\d{12,}
  ValidUserId:
    Type: String
    Description: A user ID the client has to provide as part of the URL

Resources:

  # Define IAM roles

  TriggerAlertLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      Policies:
        - PolicyName: Send
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  - "*"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  # Define the SNS Topic and SMS Subscription
  TriggerAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: ComingHome
      Subscription:
        - Endpoint: !Ref PhoneNumber
          Protocol: sms
  
  # Define the Lambda function

  TriggerAlertLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./
      Description: Function that triggers a coming alert
      MemorySize: 128
      Timeout: 15
      Tracing: Active
      Role: !GetAtt TriggerAlertLambdaRole.Arn
      Environment:
        Variables:
          TOPIC_ARN: !Ref TriggerAlertTopic
          VALID_USER_ID: !Ref ValidUserId
      Events:
        Trigger:
          Type: Api
          Properties:
            Path: /users/{userId}/trips
            Method: post
  
Outputs:

  AddTripURL:
    Description: URL for triggering a new trip
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/userId/trips"